import type { Metadata } from "next";
import Link from "next/link";
import { dictionaries, type Lang } from "@/dictionaries";

export const metadata: Metadata = {
  title: "Terms of Service — Kidsit AI",
};

const SECTIONS = [
  {
    h: "Acceptance of Terms",
    p: "By accessing or using Kidsit.ai, you agree to be bound by these Terms. If you do not agree, please do not use the App.",
  },
  {
    h: "Description of Service",
    p: "Kidsit.ai provides AI-generated parenting guidance based on information you provide. The guidance is for informational purposes only and is not a substitute for professional advice from pediatricians, therapists, or other qualified professionals.",
  },
  {
    h: "Not Medical or Professional Advice",
    p: "The App does not provide medical, psychological, or legal advice. If your child shows signs of distress, illness, or behavior requiring professional attention, consult a qualified professional. In an emergency, contact local emergency services.",
  },
  {
    h: "Your Responsibilities",
    p: "You are solely responsible for any decisions you make based on the App's suggestions. You must be at least 18 years old and the parent or legal guardian of any child you describe in the App.",
  },
  {
    h: "Acceptable Use",
    p: "You agree not to misuse the App, including: submitting false information, attempting to extract personal data about others, using the App for unlawful purposes, or attempting to disrupt the service.",
  },
  {
    h: "AI-Generated Content",
    p: "Responses are generated by third-party AI models (OpenAI, Anthropic) and may be inaccurate, incomplete, or inappropriate for your specific situation. Always apply your own judgment as a parent.",
  },
  {
    h: "Limitation of Liability",
    p: "To the maximum extent permitted by law, Kidsit.ai and its operators are not liable for any direct, indirect, incidental, or consequential damages arising from your use of the App. The App is provided \"as is\" without warranties of any kind.",
  },
  {
    h: "Changes to the Service",
    p: "We may modify, suspend, or discontinue the App at any time without notice. We may also update these Terms; continued use after changes constitutes acceptance of the updated Terms.",
  },
  {
    h: "Governing Law",
    p: "These Terms are governed by the laws of the State of Israel, without regard to conflict of law principles.",
  },
  {
    h: "Contact Us",
    p: "For questions about these Terms, you can reach us through the website.",
  },
];

export default function Terms({ params }: { params: { lang: Lang } }) {
  const t = dictionaries[params.lang].legal;
  return (
    <main dir="ltr" className="mx-auto max-w-3xl px-5 py-16 sm:px-6">
      <Link href={t.home} className="font-bold text-grape hover:underline">
        {t.back}
      </Link>
      <h1 className="mt-6 font-display text-4xl font-semibold">Terms of Service</h1>
      <p className="mt-2 text-sm font-bold text-ink/60">Last updated: March 2026</p>
      <p className="mt-6 font-bold text-ink/80">
        These Terms of Service (&quot;Terms&quot;) govern your use of Kidsit.ai (&quot;the
        App&quot;). By using the App, you agree to these Terms.
      </p>
      {SECTIONS.map((s) => (
        <section key={s.h} className="mt-8">
          <h2 className="font-display text-2xl font-semibold">{s.h}</h2>
          <p className="mt-2 font-bold text-ink/80">{s.p}</p>
        </section>
      ))}
    </main>
  );
}
